name: Postman collection workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *' # Runs at 02:30 UTC everyday
    - cron: '00 14 * * *' # Runs at 14:00 UTC everyday (7:30 PM IST)

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: install Nodejs and NPM 
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Install newman and Html-extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
             
      - name: Run the postman collection with newman
        run: |
          newman run 'In-Warranty collection Copy.postman_collection.json' \
          -e QA.postman_environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html
          
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always() # This ensures the report uploads even if the tests fail
        with:
          name: postman-html-report
          path: newman/*.html

      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
    
